package com.nicepeopleatwork.forest;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'niceportatil' at '11/3/16 3:10 PM' with Gradle 3.0
 *
 * @author niceportatil, @date 11/3/16 3:10 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    
    public static void main ( String [ ] args )
	{
		
	}
}
