import org.junit.Test;

import com.nicepeopleatwork.forest.Library;

import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'niceportatil' at '11/3/16 3:10 PM' with Gradle 3.0
 *
 * @author niceportatil, @date 11/3/16 3:10 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
